spring:
  application:
    name: spring-boot-sample
  profiles:
    active: dev
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.80.134:3306/test?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      connectionTimeout: 30000
      validationTimeout: 5000
      maxPoolSize: 200
      minIdle: 100
    slave01:
      jdbc-url: jdbc:mysql://192.168.80.135:3306/test?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      connectionTimeout: 30000
      validationTimeout: 5000
      maxPoolSize: 200
      minIdle: 100
    slave02:
      jdbc-url: jdbc:mysql://192.168.80.135:3306/test?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      connectionTimeout: 30000
      validationTimeout: 5000
      maxPoolSize: 200
      minIdle: 100


springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: true

server:
  port: 8081


#mybatis
mybatis:
  ###把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
  mapper-mapperLocations: classpath*:mapper/*.xml
  type-aliases-package: com.zhliang.pzy.spring.fox.dynamic.datasource.po
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    useGeneratedKeys: true

# redisson分布式锁
redisson:
  lock:
    server:
      address: 127.0.0.1:6379
      type: standalone
      database: 0


pzy:
  encrypt:
    rsa:
      open: true # 是否开启加密 true  or  false
      showLog: true # 是否打印加解密log true  or  false
      debug: false
      publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCMv5INQ/CdrB8rN1BSZTeOyqRO+ELTDb2SfxXN2tji+tFUlP1cCm4wFiOPybg4TA8BltX0qOXy8O49qdMlzUcs1KWg6Pu1iecTgUy+hKOyDYCmJx77e5QMcqfIsf2XSbmDbYleWKSl4TLzb0Djv1/dKcEWJC5h7kp8uwF55xkO5wIDAQAB
      privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIy/kg1D8J2sHys3UFJlN47KpE74QtMNvZJ/Fc3a2OL60VSU/VwKbjAWI4/JuDhMDwGW1fSo5fLw7j2p0yXNRyzUpaDo+7WJ5xOBTL6Eo7INgKYnHvt7lAxyp8ix/ZdJuYNtiV5YpKXhMvNvQOO/X90pwRYkLmHuSny7AXnnGQ7nAgMBAAECgYBid9wcP73k8XhU6bveCUYXNhpBzVojAefwx8xfWo6GLeepfxrJ+9oe9j4m6H9jk4KkH/zL0CYgEwL6TQeV2MnDvxwEsOpgr1K0ynAA3et7qfsgSpx1LOaVyRnF8kNGV8Grz551Vj3QZ/aUMDawwnUpw72IdnfbiFv7flFVnBTY0QJBAMzGEoXvCEkbaRavmvbafZv7skA7une/snT9M9E6hz07u8PyR6GRbZMmetoopp/9Sbt9WgYpP1Zh8i5g+ImgSmsCQQCv9T5LBg6bfCVbaUuK8pdt61FWHdNFUDAjqI30TuyQ4qnlRoaXhbXEAoJkxVSlDXu37M+aeQktKsuBVSm7ICR1AkEAvRUMl5WPfgoMcIE4Q0afA8BW6M7+MILXIwWGqmUz6YvVpmp6UCs8FctLV1R//21ffvuRe+zsajRI7yBlfpd+/wJANIK1smH+XfxwkZUczDyVYGJHhbGk6RyDIUEeC/i5tItQNHIVnIZ0tighjb0uA4vAjiUH14ujZ21MCi7GI2f2OQJAD0qKInasT7YoJuZ9goyA9XDCoIDYj3J1YSsxn492tjNa5oSE6jO5p8uOC/W2cr3CVNIjys8E244NwXMQNS95ew==

